// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMvcApp.Data;

namespace TestMvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210213174415_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestMvcApp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 2",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 2,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 1",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 3,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 3",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 4,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 4",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 5,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 5",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 6,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 6",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 7,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 7",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 8,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 8",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 9,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 9",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 10,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 10",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 11,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 11",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 12,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 12",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 13,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 14",
                            Slug = "sample-post-1"
                        },
                        new
                        {
                            Id = 14,
                            BannerUrl = "610eac01-ed19-4f6f-a513-f4e5faca1cb2_banner1.jpg",
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam quod labore asperiores minima corporis possimus accusantium odit eveniet quia itaque voluptatem voluptate sequi, officia quos praesentium placeat similique iusto iure.",
                            Name = "Sample Post 14",
                            Slug = "sample-post-1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
